require_relative 'array/after.rb'
#require_relative 'array/arrange.rb'            # too new
require_relative 'array/average.rb'
require_relative 'array/before.rb'
require_relative 'array/collapse.rb'
require_relative 'array/collisions.rb'
require_relative 'array/commonality.rb'
require_relative 'array/conjoin.rb'
require_relative 'array/contains.rb'
require_relative 'array/delete.rb'
require_relative 'array/delete_unless.rb'
require_relative 'array/delete_values.rb'
require_relative 'array/divide.rb'
require_relative 'array/duplicates.rb'
require_relative 'array/each_pair.rb'
require_relative 'array/each_value.rb'
require_relative 'array/entropy.rb'
require_relative 'array/extract_options.rb'
require_relative 'array/from.rb'
require_relative 'array/indexable.rb'
#require_relative 'array/intersection.rb'       # too new
#require_relative 'array/median.rb'             # uncommon
require_relative 'array/merge.rb'
#require_relative 'array/missing.rb'            # too new
require_relative 'array/mode.rb'
require_relative 'array/nonuniq.rb'
require_relative 'array/not_empty.rb'
require_relative 'array/only.rb'
require_relative 'array/pad.rb'
require_relative 'array/peek.rb'
#require_relative 'array/percentile.rb'         # uncommon
require_relative 'array/unique_permutation.rb'
require_relative 'array/poke.rb'
require_relative 'array/probability.rb'
require_relative 'array/pull.rb'
require_relative 'array/occurrence.rb'
#require_relative 'array/op_pow.rb'             # uncommon
require_relative 'array/recurse.rb'
require_relative 'array/recursively.rb'
require_relative 'array/reject_values.rb'
require_relative 'array/splice.rb'
require_relative 'array/split.rb'
require_relative 'array/squeeze.rb'
require_relative 'array/store.rb'
require_relative 'array/thru.rb'
require_relative 'array/to_h.rb'
require_relative 'array/traverse.rb'
require_relative 'array/uniq_by.rb'

