require_relative 'binding/caller.rb'
require_relative 'binding/callstack.rb'
require_relative 'binding/call_stack.rb'
require_relative 'binding/defined.rb'
require_relative 'binding/op.rb'
require_relative 'binding/op_get.rb'
require_relative 'binding/op_set.rb'
require_relative 'binding/self.rb'
require_relative 'binding/with.rb'
require_relative 'binding/__callee__.rb'
require_relative 'binding/__method__.rb'

