require_relative 'file/append.rb'
#require_relative 'file/atomic_write.rb'    # uncommon
require_relative 'file/common_path.rb'
require_relative 'file/create.rb'
require_relative 'file/ext.rb'
require_relative 'file/null.rb'
require_relative 'file/read_binary.rb'
require_relative 'file/read_list.rb'
require_relative 'file/rewrite.rb'
require_relative 'file/rootname.rb'
require_relative 'file/sanitize.rb'
require_relative 'file/split_all.rb'
require_relative 'file/split_root.rb'
require_relative 'file/write.rb'
require_relative 'file/writelines.rb'

