require_relative 'kernel/as.rb'
require_relative 'kernel/ask.rb'
require_relative 'kernel/assign.rb'
require_relative 'kernel/assign_from.rb'
require_relative 'kernel/attr_singleton.rb'
require_relative 'kernel/blank.rb'
require_relative 'kernel/callstack.rb'
require_relative 'kernel/call_stack.rb'
require_relative 'kernel/case.rb'
require_relative 'kernel/complete.rb'
require_relative 'kernel/constant.rb'
require_relative 'kernel/d.rb'
require_relative 'kernel/deep_clone.rb'
require_relative 'kernel/deep_copy.rb'
#require_relative 'kernel/demo.rb'              # uncommon
require_relative 'kernel/disable_warnings.rb'
require_relative 'kernel/eigen.rb'
#require_relative 'kernel/eigenclass.rb'        # uncommon
require_relative 'kernel/enable_warnings.rb'
#require_relative 'kernel/equate.rb'
require_relative 'kernel/ergo.rb'
require_relative 'kernel/extend.rb'
require_relative 'kernel/extension.rb'
require_relative 'kernel/false.rb'
require_relative 'kernel/here.rb'
#require_relative 'kernel/hierarchical_send'    # uncommon
require_relative 'kernel/identical.rb'
require_relative 'kernel/in.rb'
require_relative 'kernel/instance_assign.rb'
require_relative 'kernel/instance_class.rb'
#require_relative 'kernel/instance_exec.rb'     # uncommon
require_relative 'kernel/instance_extract.rb'
require_relative 'kernel/instance_replace.rb'
require_relative 'kernel/instance_send.rb'
require_relative 'kernel/like.rb'
require_relative 'kernel/load_all.rb'
require_relative 'kernel/load_relative.rb'
require_relative 'kernel/maybe.rb'
#require_relative 'kernel/memo.rb'              # uncommon
require_relative 'kernel/meta_alias.rb'
require_relative 'kernel/meta_class.rb'
require_relative 'kernel/meta_def.rb'
require_relative 'kernel/meta_eval.rb'
require_relative 'kernel/method.rb'
require_relative 'kernel/no.rb'
require_relative 'kernel/not.rb'
require_relative 'kernel/not_nil.rb'
require_relative 'kernel/object_class.rb'
require_relative 'kernel/object_hexid.rb'
require_relative 'kernel/object_send.rb'
require_relative 'kernel/p.rb'
require_relative 'kernel/presence.rb'
require_relative 'kernel/present.rb'
require_relative 'kernel/qua_class.rb'
require_relative 'kernel/require_all.rb'
require_relative 'kernel/respond.rb'
require_relative 'kernel/returning.rb'
require_relative 'kernel/silence.rb'
require_relative 'kernel/silence_warnings.rb'
require_relative 'kernel/singleton_class.rb'
require_relative 'kernel/super_method.rb'
require_relative 'kernel/tap.rb'
require_relative 'kernel/temporarily.rb'
#require_relative 'kernel/trap_chain.rb'        # uncommon
require_relative 'kernel/true.rb'
require_relative 'kernel/try.rb'
require_relative 'kernel/val.rb'
require_relative 'kernel/with.rb'
require_relative 'kernel/writers.rb'
#require_relative 'kernel/y.rb'                 # uncommon
require_relative 'kernel/yes.rb'
require_relative 'kernel/__class__.rb'
require_relative 'kernel/__dir__.rb'
require_relative 'kernel/__get__.rb'
require_relative 'kernel/__set__.rb'

