require_relative 'time/ago.rb'
require_relative 'time/change.rb'
require_relative 'time/dst_adjustment.rb'
require_relative 'time/elapse.rb'
require_relative 'time/future.rb'
require_relative 'time/hence.rb'
require_relative 'time/in.rb'
require_relative 'time/less.rb'
require_relative 'time/past.rb'
require_relative 'time/round_to.rb'
require_relative 'time/set.rb'
require_relative 'time/shift.rb'
require_relative 'time/stamp.rb'
require_relative 'time/to_time.rb'
require_relative 'time/trunc.rb'

