#!/usr/bin/env ruby

require 'fileutils'

PATH = "lib/core:lib/standard"

metadata = YAML.load_file('.ruby')
version  = metadata['version']

common_yardopts = %{
  --no-yardopts
  --no-cache
  --title "Ruby Facets"
  --readme README.rdoc
  --protected
  --private
  --tag uncommon:Uncommon
  --tag standard:Standard
}.gsub("\n", ' ')

# yard core extensions
file "lib/core/**/*.rb" do
  FileUtils.mkdir_p("web/docs/facets-#{version}")
  cmd = "shomen yard #{common_yardopts} lib/core - [A-Z]*.* > web/docs/facets-#{version}/core.json"
  abort unless system cmd
end

# yard standard extensions
file "lib/standard/**/*.rb" do
  FileUtils.mkdir_p("web/docs/facets-#{version}")
  cmd = "shomen yard #{common_yardopts} lib/standard - [A-Z]*.* > web/docs/facets-#{version}/standard.json"
  abort unless system cmd
end


=begin
#
# GENERATE RDOCS
# ----------------------------------------------------------------------------

desc "generate rdocs"
task "rdoc" do
  TEMPLATE  = ENV['RDOC_TEMPLATE'] || 'html'
  APIOUT    = "web/docs/rdoc"

  FileUtils.rm_r(APIOUT)

  system "rdoc -a -S -t'Facets Core API' -T #{TEMPLATE} -m README.rdoc --op '#{APIOUT}/core' README.rdoc lib/facets/core"
  system "rdoc -a -S -t'Facets Standard API' -T #{TEMPLATE} -m README.rdoc --op '#{APIOUT}/standard' README.rdoc lib/facets/standard"
end
=end

#
# RUN TESTS (requires Lemon)
# ----------------------------------------------------------------------------
#
# TODO: Run only the tests correpsonding to the changed files.
#

file "lib/**/*.rb" do
  sh "ruby-test #{test_flags} test/"
end

file "test/**/*.rb" do |f|
  p f
  #sh "ruby-test #{test_flags} #{tests}"
end

#desc "run all unit tests with ActiveSupport loaded"
#task 'test:all:activesupport' => [:include_activesupport, 'test:all']

#desc "run core unit tests with ActiveSupport loaded"
#task 'test:core:activesupport' => [:include_activesupport, 'test:core']

#desc "run standard unit tests with ActiveSupport loaded"
#task 'test:standard:activesupport' => [:include_activesupport, 'test:standard']

#task 'include_activesupport' do
#  require 'activesupport'
#end

def test_flags
  flags = []
  if ENV['verbose']
    flags << '-v'
  end
  flags.join(' ')
end

