#!/usr/bin/env ruby

require 'fileutils'

metadata = YAML.load_file('.ruby')
version  = metadata['version']

common_yardopts = %{
  --no-yardopts
  --no-cache
  --title "Ruby Facets"
  --readme README.rdoc
  --protected
  --private
  --tag uncommon:Uncommon
  --tag standard:Standard
}.gsub("\n", ' ')

desc "Generate shomen documentation"
task :document do
  FileUtils.mkdir_p("web/docs/facets-#{version}")
  system "shomen yard #{common_yardopts} lib/core - [A-Z]*.* > web/docs/facets-#{version}/core.json"
  system "shomen yard #{common_yardopts} lib/standard - [A-Z]*.* > web/docs/facets-#{version}/standard.json"
end

# yard core extensions
file "lib/core/**/*.rb" do
  #cmd = "yard "
  #cmd << "-o site/doc/yard/core "
  ##cmd << "--title 'Facets Core Extensions' "
  #cmd << "-r doc/README.core "
  #cmd << "lib/core - README.rdoc AUTHORS.rdoc NOTICE.rdoc "
  #abort unless system cmd
  abort unless system "shomen yard #{common_yardopts} lib/core - [A-Z]*.* > web/docs/facets-#{version}/core.json"
end

# yard standard extensions
file "lib/standard/**/*.rb" do
  #cmd = "yard "
  #cmd << "-o site/doc/yard/standard "
  ##cmd << "--title 'Facets Standard Extensions' "
  #cmd << "-r doc/README.standard "
  #cmd << "lib/standard - README.rdoc AUTHORS.rdoc NOTICE.rdoc "
  #abort unless system cmd
  abort unless system "shomen yard #{common_yardopts} lib/standard - [A-Z]*.* > web/docs/facets-#{version}/standard.json"
end


=begin
#
# GENERATE RDOCS
# ----------------------------------------------------------------------------

desc "generate rdocs"
task "rdoc" do
  TEMPLATE  = ENV['RDOC_TEMPLATE'] || 'html'
  APIOUT    = "web/docs/rdoc"

  FileUtils.rm_r(APIOUT)

  system "rdoc -a -S -t'Facets Core API' -T #{TEMPLATE} -m README.rdoc --op '#{APIOUT}/core' README.rdoc lib/facets/core"
  system "rdoc -a -S -t'Facets Standard API' -T #{TEMPLATE} -m README.rdoc --op '#{APIOUT}/standard' README.rdoc lib/facets/standard"
end
=end

