#!/usr/bin/env ruby

dir = 'packages'

Dir.chdir(dir)

files = Dir.glob('**/facets/*.rb')

assoc_names = []
files.each do |f|
  assoc_names << [File.basename(f), f]
end

# Duplicates
dups = []
last = ''

assoc_names = assoc_names.sort_by{ |a,b| a[0] <=> b[0] }

last_name = ''
last_file = ''

assoc_names.each do |name, file|
  if last_name == name
    dups << last_file
    dups << file
  end
  last_name = name
  last_file = file
end

# Names

names = assoc_names.collect{ |a| a[0] }

puts names.uniq.join("\n")
puts

if dups.size > 0
  puts "#{dups.size} duplicates exist!"
  dups.each do |d|
    puts "  #{d}"
  end
  puts
end

puts "#{names.size} total scripts."

